using System;
using System.Collections.Generic;
using System.Linq;
using MongoDB.Bson;
using Yeasca.Metier;

namespace Yeasca.Mongo
{
    public class EntrepotParametrage : IEntrepotParametrage
    {
        private IFournisseur _fournisseur;

        public EntrepotParametrage(IFournisseur fournisseur)
        {
            _fournisseur = fournisseur;
        }

        public bool ajouter(IAgregat agrégat)
        {
            throw new NotImplementedException();
        }

        public bool modifier(IAgregat agrégat)
        {
            throw new NotImplementedException();
        }

        public IList<string> récupérerLesRépétitionDeVoie()
        {
            return
                new List<string>()
                {
                    "Bis",
                    "Ter",
                    "Quarter",
                    "Quinquies"
                };
        }

        public IList<string> récupérerLesTypesDeVoie()
        {
            return
            #region Valeurs
                new List<string>()
                {
                    "Abbaye abe",
                    "Agglomeration agl",
                    "Aire aire",
                    "Aires aire",
                    "Allee all",
                    "Allees all",
                    "Ancien chemin",
                    "Ancien-chemin",
                    "Ancienne montee",
                    "Ancienne route",
                    "Ancienne-montee",
                    "Ancienne-route",
                    "Anciennesroutes",
                    "Anciennes-routes",
                    "Anciens chemins",
                    "Anciens-chemins",
                    "Anse",
                    "Arcade",
                    "Arcades",
                    "Autoroute",
                    "Avenue",
                    "Barriere",
                    "Barrieres",
                    "Bas chemin",
                    "Bas-chemin",
                    "Bastide",
                    "Bastion",
                    "Beguinage",
                    "Beguinages",
                    "Berge",
                    "Berges",
                    "Bois",
                    "Boucle",
                    "Boulevard",
                    "Bourg",
                    "Butte",
                    "Bvd",
                    "Cale",
                    "Camp",
                    "Campagne",
                    "Camping",
                    "Carre",
                    "Carreau",
                    "Carrefour",
                    "Carriere",
                    "Carrieres",
                    "Castel",
                    "Cavee",
                    "Central",
                    "Centre",
                    "Centre cial",
                    "Centre com",
                    "Centre comm",
                    "Centre commercial",
                    "Chalet",
                    "Chapelle",
                    "Charmille",
                    "Chateau",
                    "Chaussee",
                    "Chaussees",
                    "Chem",
                    "Chemin",
                    "Chemin vicinal",
                    "Cheminement",
                    "Cheminements",
                    "Chemins",
                    "Chemins vicinaux",
                    "Chemins-vicinaux",
                    "Chemin-vicinal",
                    "Chez",
                    "Cite",
                    "Cites",
                    "Cloitre",
                    "Clos",
                    "Col",
                    "Colline",
                    "Collines",
                    "Contour",
                    "Corniche",
                    "Corniches",
                    "Cote",
                    "Coteau",
                    "Coteaux",
                    "Cottage",
                    "Cottages",
                    "Cour",
                    "Cours",
                    "Ctre cial",
                    "Ctre com",
                    "Ctre comm",
                    "Ctre commercial",
                    "Darse",
                    "Degre",
                    "Degres",
                    "Descente",
                    "Descentes",
                    "Digue",
                    "Digues",
                    "Domaine",
                    "Domaines",
                    "Ecluse",
                    "Ecluses",
                    "Eglise",
                    "Enceinte",
                    "Enclave",
                    "Enclos",
                    "Escalier",
                    "Escaliers",
                    "Espace",
                    "Esplanade",
                    "Esplanades",
                    "Etang",
                    "Fbg",
                    "Faubourg",
                    "Ferme",
                    "Fermes",
                    "Fontaine",
                    "Fort",
                    "Forum",
                    "Fosse",
                    "Fosses",
                    "Foyer",
                    "Galerie",
                    "Galeries",
                    "Gare",
                    "Garenne",
                    "Grand boulevard",
                    "Grand ensemble",
                    "Grandrue",
                    "Grand-boulevard",
                    "Grande rue",
                    "Grand-ensemble",
                    "Grande-rue",
                    "Grandes rues",
                    "Grandes-rues",
                    "Grand-rue",
                    "Grands ensembles",
                    "Grands-ensembles",
                    "Grille",
                    "Grimpette",
                    "Groupe",
                    "Groupement",
                    "Groupes",
                    "Halle",
                    "Halles",
                    "Hameau",
                    "Hameaux",
                    "Haut chemin",
                    "Haut-chemin",
                    "Hauts chemins",
                    "Hauts-chemins",
                    "Hippodrome",
                    "Hlm",
                    "Ile",
                    "Immeuble",
                    "Immeubles",
                    "Impasse",
                    "Impasses",
                    "Jardin",
                    "Jardins",
                    "Jetee",
                    "Jetees",
                    "Levee",
                    "Lieudit",
                    "Lieu-dit",
                    "Lotissement",
                    "Lotissements",
                    "Mail",
                    "Maison forestiere",
                    "Maison-forestiere",
                    "Manoir",
                    "Marche",
                    "Marches",
                    "Mas",
                    "Metro",
                    "Montee",
                    "Montees",
                    "Moulin",
                    "Moulins",
                    "Musee",
                    "Nouvelle route",
                    "Palais",
                    "Parc",
                    "Parcs",
                    "Parking",
                    "Parvis",
                    "Passage",
                    "Passage a niveau",
                    "Passage-a-niveau",
                    "Passe",
                    "Passerelle",
                    "Passerelles",
                    "Passes",
                    "Patio",
                    "Pavillon",
                    "Pavillons",
                    "Peripherique",
                    "Peristyle",
                    "Petit chemin",
                    "Petit degre",
                    "Petit-chemin",
                    "Petit-degre",
                    "Petite allee",
                    "Petite avenue",
                    "Petite impasse",
                    "Petite route",
                    "Petite rue",
                    "Petite-allee",
                    "Petite-avenue",
                    "Petite-impasse",
                    "Petite-route",
                    "Petite-rue",
                    "Petites allees",
                    "Petites-allees",
                    "Petits degres",
                    "Petits-degres",
                    "Place",
                    "Placis",
                    "Plage",
                    "Plages",
                    "Plaine",
                    "Plan",
                    "Plateau",
                    "Plateaux",
                    "Pont",
                    "Ponts",
                    "Porche",
                    "Port",
                    "Porte",
                    "Portique",
                    "Portiques",
                    "Poterne",
                    "Pourtour",
                    "Pre",
                    "Presqu ile",
                    "Presqu'ile",
                    "Presqu-ile",
                    "Promenade",
                    "Qrt",
                    "Quai",
                    "Quartier",
                    "Raccourci",
                    "Raidillon",
                    "Rampe",
                    "Rempart",
                    "Rpr",
                    "Residence",
                    "Residences",
                    "Roc",
                    "Rocade",
                    "Rond point",
                    "Rond-point",
                    "Roquet",
                    "Rotonde",
                    "Route",
                    "Routes",
                    "Rue",
                    "Ruelle",
                    "Ruelles",
                    "Rues",
                    "Sente",
                    "Sentes",
                    "Sentier",
                    "Sentiers",
                    "Square",
                    "Stade",
                    "Station",
                    "Str",
                    "Terrain",
                    "Terrasse",
                    "Terrasses",
                    "Terre plein",
                    "Terre-plein",
                    "Tertre",
                    "Tertres",
                    "Traverse",
                    "Val",
                    "Vallee",
                    "Vallon",
                    "Venelle",
                    "Venelles",
                    "Via",
                    "Vieille route",
                    "Vieille-route",
                    "Vieux chemin",
                    "Vieux-chemin",
                    "Villa",
                    "Village",
                    "Villages",
                    "Villas",
                    "Voie",
                    "Voie communale",
                    "Voie-communale",
                    "Voies",
                    "Zone",
                    "Zone a urbaniser en priorite",
                    "Zone artisanale",
                    "Zone d amenagement concerte",
                    "Zone d amenagement differe",
                    "Zone d'amenagement concerte",
                    "Zone d'amenagement differe",
                    "Zone indus",
                    "Zone industrielle",
                    "Zone-artisanale"
                };
#endregion
        }

        public IDictionary<TypeUtilisateur, string> récupérerLesTypesUtilisateurs()
        {
            return new Dictionary<TypeUtilisateur, string>()
            {
                {TypeUtilisateur.Huissier, Ressource.Paramètres.LIBELLÉ_HUISSIER},
                {TypeUtilisateur.Secrétaire, Ressource.Paramètres.LIBELLÉ_SECRÉTAIRE}
            };
        }

        public IDictionary<Abreviation, string> récupérerLesCivilités()
        {
            return new Dictionary<Abreviation, string>()
            {
                {Abreviation.Mademoiselle, Ressource.Paramètres.MADEMOISELLE},
                {Abreviation.Madame, Ressource.Paramètres.MADAME},
                {Abreviation.Monsieur, Ressource.Paramètres.MONSIEUR}
            };
        }
    }

    public class ParametreMongo : IAgregat
    {
        public ObjectId _id { get; set; }
        public Guid Id { get; set; }
        public string Valeur { get; set; }
    }

    public class ParametreRepetition : ParametreMongo { }
    public class ParametreTypeVoie : ParametreMongo { }
}
